-- Deploy ofrigo:2.insert to pg

BEGIN;

--INSERT INTO account(last_name, first_name, email, password, role) VALUES
--('lienard', 'kevin', 'kevin@gmail.com', '1234', 'admin');

--INSERT INTO message(title, content, email) VALUES
--('test', 'Ceci est un test', 'antoine_Peral@gmail.com');

INSERT INTO category(label) VALUES
('Légumes'),
('Poissons'),
('Viandes'),
('Fruits'),
('Epicerie'),
('Crémerie'),
('Fruits de mer'),
('Oeufs');

INSERT INTO ingredient(label, unit, category_id) VALUES
('Farine', 'mg', 5),
('Levure chimique', 'paquet', 5),
('Beurre', 'mg', 6),
('Banane', null, 4),
('Chocolat', 'mg', 5),
('Cardamome', 'pincée', 5),
('Cassonade', 'mg', 5),
('Oeuf', null, 8),
('Lait', 'ml', 6),
('Sel', null, 5),
('Sucre en poudre', 'mg', 5),
('Grand-marnier ou de rhum', null, 5),
('Pralin', 'pincée', 5),
('Glace vanille', 'boule', 6),
('Pâte brisée', 'rouleau', 5),
('Crème fraîche', 'mg', 6),
('Lardons', 'mg', 3),
('Poivre', null, 5),
('Muscade', null, 5),
('Fond de veau', 'ml', 5),
('Comté', 'mg', 6),
('Maïzena', null, 5),
('Bar', 'mg', 2),
('Chorizo', 'mg', 3),
('Chapelure', 'mg', 5),
('Carotte', 'mg', 1),
('Courgette', null, 1),
('Cumin', 'c.à.s', 5),
('Patate douce ', 'c.à.s', 1),
('Echalotes', null, 1),
('Ail', 'gousses', 1),
('Crème coco', 'ml', 6),
('Pâte de curry rouge', 'mg', 5),
('Concentré de tomate', 'c.à.s', 5),
('Citron vertes', null, 1);

INSERT INTO recipe(label, picture, rate, difficulty, time) VALUES
('Cake du petit-déjeuner banane-chocolat', './', 4.4, 'Très facile', '45 min'),
('Pâte à crêpes (des plus raffinées)', './', 4.7, 'Facile', '17 min'),
('Bowl cake moelleux chocolat noisettes', './', 4.5, 'Très facile', '13 min'),
('Quiche lorraine traditionnelle', './', 4.8, 'Très facile', '35 min'),
('Filet de bar en croûte de chorizo, purée et mousse de haricots cocos de Paimpol', './', 4.2, 'Moyenne', '2 h 30 min'),
('Curry de légumes végétarien', './', 4.8, 'Très facile', '1 h 20 min');

INSERT INTO step(content, number, recipe_id) VALUES
('Préchauffer le four à 220°C (thermostat 7).', 1, 1),
('Dans un saladier, mélanger la farine, la levure, la cassonade, l''oeuf, le beurre, la banane coupée en petits dés, le chocolat coupés en pépites, le lait et la cardamome.', 2, 1),
('Verser dans un plat à cake souple de préférence et enfourner pour 30 minutes.', 3, 1),
('Au bout de ce temps, la pointe du couteau plantée dans le cake doit ressortir sèche !', 4, 1),
('Dans un saladier, mélanger la farine, le sel et le sucre.', 1, 2),
('Faire une fontaine.', 2, 2),
('Ajouter les oeufs et commencer à les incorporer à la farine avec une cuillère en bois, ajouter le beure fondu (tiédi) peu à peu et bien malaxer.', 3, 2),
('Incorporer le lait (par petites quantités au début pour éviter les grumeaux), ajouter le parfum.', 4, 2),
('Faire cuire les crêpes dans une poêle chaude huilée.', 5, 2),
('Dans un bol (de la taille du moelleux souhaité) couper le chocolat en morceaux et faire fondre avec le lait au micro-ondes.', 1, 3),
('Mélanger avec une fourchette jusqu''à ce que le chocolat soit bien fondu.', 2, 3),
('Ajouter le sucre, les oeufs et la purée de noisettes et bien mélanger.', 3, 3),
('Ajouter la poudre de noisettes et la levure. Mélanger jusqu''à l''obtention d''un mélange homogène.', 4, 3),
('Cuire 2min30 au micro-ondes.', 5, 3),
('Le dessus du moelleux doit être tout juste cuit, si besoin, remettre 30 secondes de cuisson.', 6, 3),
('Pour démouler, renverser le bol et servir encore chaud avec une boule de glace et une pincée de pralin.', 7, 3),
('Pré-chauffer le four à 200°C (thermostat 6-7). Dérouler la pâte brisée et la placer dans un plat à tarte. Piquer le fond avec une fourchette.', 1, 4),
('Faire dorer les lardons.', 2, 4),
('Pendant ce temps, mélanger les oeufs battus et la crème fraîche.', 3, 4),
('Une fois les lardons dorés, les mélanger à la préparation aux oeufs.', 4, 4),
('Saler, poivrer, et ajouter la muscade selon votre convenance.', 5, 4),
('Verser la préparation sur le fond de pâte.', 6, 4),
('Mettre au four pendant 30 min.', 7, 4),
('Préparez la croûte de chorizo : détaillez-en 50 g très finement à l’aide d’un couteau ou d’un robot ménager.', 1, 5),
('Mélangez le fromage râpé, la chapelure et le chorizo.', 2, 5),
('Ajoutez le beurre à l’aide d’une fourchette, rectifiez l''assaisonnement et roulez en boule.', 3, 5),
('Entreposez au réfrigérateur pendant quelques heures.', 4, 5),
('Par ailleurs, faites sécher 4 tranches de chorizo, sur une grille à pâtisserie, au four préchauffé à 80°C : les tranches doivent sécher et devenir croustillantes.', 5, 5),
('Réservez sur une grille.', 6, 5),
('Selon le conditionnement des cocos (bocal ou sec), réhydratez-les selon les indications de l’emballage et faites-les cuire ou réchauffer.', 7, 5),
('Par ailleurs, coupez le reste de chorizo en morceaux et mettez-les dans un poêlon avec le fond de veau.', 8, 5),
('Faites réduire de ¾ et passez le jus restant au chinois fin.', 9, 5),
('Réservez la moitié des haricots et passez le reste au robot ménager avec un peu de crème fraîche et de lait afin d’obtenir une purée très fine (adaptez la quantité pour obtenir une purée bien lisse et onctueuse).', 10, 5),
('Passez la purée au chinois fin.', 11, 5),
('Assaisonnez de noix de muscade, de poivre et de sel.', 12, 5),
('La purée doit être lisse et sans grumeaux.', 13, 5),
('Rectifiez l''assaisonnement.', 14, 5),
('Découpez le filet de poisson en 4 morceaux égaux.', 15, 5),
('Réservez au frais.', 16, 5),
('Retirez la pâte du réfrigérateur, laissez-la se détendre un peu et abaissez-la au rouleau à environ 3 mm entre 2 feuilles de papier cuisson.', 17, 5),
('Découpez cette abaisse aux dimensions des morceaux de poissons.', 18, 5),
('Préchauffez le four à 180°C (thermostat 6).', 19, 5),
('Disposez les morceaux de poisson dans un plat beurré, salez, poivrez et enfournez-les.', 20, 5),
('Faites cuire environ 10 minutes.', 21, 5),
('Retirez du four et laissez refroidir un peu.', 22, 5),
('Disposez les tranches de préparation sur les morceaux de poissons.', 23, 5),
('Remettez au four, en position grill et laissez colorer la croûte.', 24, 5),
('Réchauffez la sauce et ajoutez, le cas échéant, un peu de maïzena à la réduction de fond de veau et montez la sauce au beurre.', 25, 5),
('Versez les cocos entiers dans un poêlon avec un peu de beurre, salez, poivrez et faites-les réchauffer à feu doux.', 26, 5),
('Versez la crème de coco dans un siphon préalablement chauffé à l’eau.', 27, 5),
('Fermez et vissez 2 cartouches de gaz.', 28, 5),
('Si vous ne disposez pas d’un siphon, versez simplement la crème de cocos à l’aide d’ une cuillère à soupe.', 29, 5),
('Versez 2 cuillères à soupe de cocos au centre de l’assiette, disposez un morceau de poisson couvert de croûte dessus.', 30, 5),
('Versez le fond réduit d’un côté et siphonné un peu de crème de coco de l’autre.', 31, 5),
('Décorez d’une tranche de chorizo séchée.', 32, 5),
('Débiter les carottes en fines tranches et la patate en petits morceaux. Découper les courgettes en quarts de rondelles tout en conservant la peau.', 1, 6),
('Détailler les échalotes et l''ail et les faire dorer dans une grande sauteuse avec un peu d''huile. Ajouter les légumes, réduire le feu et couvrir.', 2, 6),
('En parallèle, dans un saladier, mélanger la crème de coco, le concentré de tomates et la pâte de curry avec le jus des citrons verts. Ajouter le piment et le basilic moulus, le cumin, et napper les légumes de ce mélange bien homogène. Ajouter 1/2 verre d''eau.', 3, 6),
('Poivrer et saler à discrétion.', 4, 6),
('Bien laisser mijoter sous couvercle à feu minimum.', 5, 6);

INSERT INTO tag(label) VALUES
('Petit déjeuner'),
('Entrées'),
('Apéro dinatoire'),
('Plats principal'),
('Plats Rapide'),
('Desserts'),
('Végétarien'),
('Salades'),
('Soupes'),
('Gâteaux'),
('Boisson'),
('Cocktails'),
('Pâtes, riz, semoule'),
('Plats au fromage');

--INSERT INTO account_has_ingredient(account_id, ingredient_id) VALUES

INSERT INTO recipe_has_ingredient_with_quantity(recipe_id, ingredient_id, ingredient_quantity) VALUES
(1, 1, 180000),
(1, 2, 1/2),
(1, 3, 20000),
(1, 4, 1),
(1, 5, 40000),
(1, 6, 1),
(1, 7, 70000),
(1, 8, 1),
(1, 9, 60),
(2, 1, 375000),
(2, 10, 3),
(2, 11, 75000),
(2, 3, 90000),
(2, 8, 6),
(2, 9, 1000),
(2, 12, 3),
(3, 13, 1),
(3, 14, 1),
(4, 15, 1),
(4, 16, 250000),
(4, 17, 150000),
(4, 18, null),
(4, 10, null),
(4, 8, 3),
(4, 19, null),
(5, 20, 400),
(5, 3, 50000),
(5, 21, 50000),
(5, 16, null),
(5, 22, null),
(5, 18, null),
(5, 10, null),
(5, 23, 300000),
(5, 24, 100000),
(5, 25, 40000),
(5, 19, null),
(6, 26, 400000),
(6, 27, 2),
(6, 28, 1/2),
(6, 18, null),
(6, 10, null),
(6, 29, 1),
(6, 30, 3),
(6, 31, 3),
(6, 32, 300),
(6, 33, 50000),
(6, 34, 2),
(6, 35, null);

INSERT INTO recipe_has_tag(recipe_id, tag_id) VALUES
(1, 1),
(2, 3),
(3, 4),
(3, 13),
(4, 4),
(5, 4),
(4, 4),
(4, 7);

COMMIT;
